// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khmrelkhwoqhojektvyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtobXJlbGtod29xaG9qZWt0dnlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMjk1MjYsImV4cCI6MjA2NDgwNTUyNn0.pbVxtWoYGF4H9vsyk1uTKU8mmyAKZ25GEaY68-erRl8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);